name: meta_expression_annotation
description: A meta-expression is a code generator-based metaprogramming feature that uses function notation to denote a meta-expression.
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
